### ISSUE TITLE
Output notebook stuck at running

### ISSUE THREAD

**Issue by robertritz** [voila-dashboards/voici#103]
## Description

I'm trying a very small example to see how voici works and I'm not able to get a basic notebook to render. After running the voici command I just see "Running" on the resulting output.

## Reproduce

I created a very simple notebook that reads a small CSV file and makes a simple plot using the built in Pandas plotting tool (which uses Matplotlib). 

I placed the notebook and the CSV file in a folder called test, then ran this command from the folder above test:
```
voici build --contents test
```
After launching the web server with `python -m http.server 8000 --directory _output` I click on the notebook. It is stuck on the Running... screen. 

I'm really not sure what is going on here.

## Context

- voila version: 0.5.5
- Operating System and version: Mac osX
- Browser and version: Chrome 120
- Using the VS Code Jupyter extension to author the notebook

**Comment by trungleduc** [comment]
Hi, could you open the console log of your browser and post the error log here?

**Comment by robertritz** [comment]
Here is the console log. Thanks for the fast response. 

[[:]-1702640936468.log](https://github.com/voila-dashboards/voici/files/13684768/-1702640936468.log)

Also I've added a picture of the output. 

<img width="1197" alt="image" src="https://github.com/voila-dashboards/voici/assets/2746091/30d4545e-8041-4824-a3d2-20bc330e840b">

**Comment by trungleduc** [comment]
There are 2 issues:
- "No kernel available" -> You need to install `jupyterlite-xeus-python`
- "Service worker not supported in this browser" -> voici uses service worker to get access to your CSV file.

**Comment by jtpio** [comment]
> "Service worker not supported in this browser" -> voici uses service worker to get access to your CSV file.

Expanding a bit on this: Service Worker might not be available in some situations, such as in a Firefox Private window. Some of these limitations are currently known and listed here: https://jupyterlite.readthedocs.io/en/stable/howto/configure/advanced/service-worker.html#limitations

**Comment by trungleduc** [comment]
This should be fixed in 0.6.0. Please feel free to re-open if needed.
