### ISSUE TITLE
Missing scripts to build the documentation?

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voici#112]
## Description

Looks like the scripts to build the documentation (added in https://github.com/voila-dashboards/voici/pull/60) are now missing from the top-level `pyproject.toml`?

https://github.com/voila-dashboards/voici/blob/8d310fe41105114dac94dd1007e664c7acb32327/pyproject.toml#L1-L24

While they are still mentioned in the contributing guide:

https://github.com/voila-dashboards/voici/blob/main/CONTRIBUTING.md#documentation

![image](https://github.com/voila-dashboards/voici/assets/591645/ba3e1f04-8dae-462e-922f-adc72732ad88)

## Reproduce

https://github.com/voila-dashboards/voici/blob/8d310fe41105114dac94dd1007e664c7acb32327/pyproject.toml#L1-L24

## Expected behavior

It should be possible to build the docs locally easily.

## Context

Re-add scripts from #60?

**Comment by martinRenou** [comment]
Probably yes. Might have been an oversight
