### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by parthi2929** [voila-dashboards/voici#115]
## Description

When I try to run [voici-demo](https://github.com/voila-dashboards/voici-demo), creating a new repo as [here](https://github.com/parthi2929/sujan-industries/tree/main), it fails for [demo.ipynb](https://parthi2929.github.io/sujan-industries/voici/render/demo.html?).   

![image](https://github.com/voila-dashboards/voici/assets/11896263/ee29ab52-c4c7-48a6-a1f3-03225e8f4b08)

## Reproduce

1. Create new repo from voice-demo
2. Trigger Github actions
3. Go to your github page of this repo

## Expected behavior

The page should be rendered fine.

**Comment by martinRenou** [comment]
> if possible to document what [build-environment](https://github.com/voila-dashboards/voici-demo/blob/main/build-environment.yml) file is for, while we already have [environment](https://github.com/voila-dashboards/voici-demo/blob/main/environment.yml) file. I tried packages for my notebook in both files

The build-environment file is the build environment spec: the environment from which you build the voici dashboard. You usually won't update it much unless you want a specific version of jupyterlite or voici.

The environment one is the one specifying the runtime package for your notebook, this is where you'll put bqplot.

When I run your example, I see different issues than you (bqplot seems properly installed, you are missing more runtime dependencies it seems):

![Screenshot from 2024-04-17 09-20-16](https://github.com/voila-dashboards/voici/assets/21197331/918c5d54-beb5-4c96-bdb6-c31010119457)

I believe you may be hitting cache, a private window may help you.

**Comment by martinRenou** [comment]
Closing as answered, but feel free to continue the discussion if needed!

**Comment by parthi2929** [comment]
I do not know what happened but now [demo.ipynb](https://github.com/parthi2929/sujan-industries/blob/b4e21e20698b4f9c9b09e4c69b48836b17c148ed/content/demo.ipynb) works, but my [Sujan 03.ipynb](https://github.com/parthi2929/sujan-industries/blob/b4e21e20698b4f9c9b09e4c69b48836b17c148ed/content/Sujan-03.ipynb) not working, even with `pyvis` included in [environment.yml](https://github.com/parthi2929/sujan-industries/blob/b4e21e20698b4f9c9b09e4c69b48836b17c148ed/environment.yml) (this is also reason, I tried adding also in [build-environemnt.yml](https://github.com/parthi2929/sujan-industries/blob/b4e21e20698b4f9c9b09e4c69b48836b17c148ed/build-environment.yml) earlier to see if that could help.. 

What do you mean by hitting a cache here, as its github actions, nothing in my local machine?

**Comment by martinRenou** [comment]
> What do you mean by hitting a cache here, as its github actions, nothing in my local machine?

Your browser caches data all the time (that way, coming to the same page multiple times will not re-download those data).

The problem with this and jupyterlite/voici is that sometimes the cached data is outdated (your browser cached a kernel with a set of package that is not containing everything you want).

You can either clean the browser cache, or visit the page with a private window (which does not make use of caching).

**Comment by parthi2929** [comment]
I am still getting error, but this time, that `template.html` file not found. Initially of course I thought I am not providing that file, but I did not get this error locally in my system. The respective notebook is [here](https://parthi2929.github.io/sujan-industries/voici/render/Sujan-03.html?).. 

If working in my local env Jupyter lab but not in voici, I am not able to debug why..

**Comment by parthi2929** [comment]
To add more context, when pyvis installed, the `template.html` should be found in below relative path in python environment where the pyvis package is installed..  (at least that is how it is in my conda env)

![image](https://github.com/voila-dashboards/voici/assets/11896263/355b0fbc-fdf1-414c-858e-959df83e7606) 

I tried the following code, in the beginning of [notebook](https://github.com/parthi2929/sujan-industries/blob/main/content/Sujan-03.ipynb), which prints that `template.html` does indeed exist for my local system in my conda env.. 

```python
import importlib.resources as pkg_resources
from pathlib import Path

def find_template_in_package(package, filename="template.html"):
    # Access the package's resources
    package_files = pkg_resources.files(package)
    # Convert to a Path object to use pathlib operations
    directory = Path(package_files)
    # Search recursively for the file
    for path in directory.rglob(filename):
        return path
    return None

# Package from which to find the file
package = __import__('pyvis')

# Search for the 'template.html' file
template_path = find_template_in_package(package)

if template_path:
    print(f"'template.html' found at: {template_path}")
else:
    print("No 'template.html' file found in the pyvis package.")

```
![image](https://github.com/voila-dashboards/voici/assets/11896263/298e8fa5-1c41-4923-a30c-5378894b182e)

But when we access it online, voici renders that its not found.. 
![image](https://github.com/voila-dashboards/voici/assets/11896263/e2c853d5-2660-45d8-ae02-60d176603450)

This indicates, that some how this `template.html` (and may be some more assets like this?) not becoming available via voici..  

Kindly help..

**Comment by martinRenou** [comment]
Thank you for the detailed issue, this is really useful!

I think empack is filtering out the HTML files from pyvis, https://github.com/emscripten-forge/empack/pull/96 should fix this!
