### ISSUE TITLE
Dark theme is not applied immediately

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voici#29]
## Description
![dark-theme](https://user-images.githubusercontent.com/4451292/222765858-f965de88-5aaa-465e-bd7a-8f471d4137b6.gif)

## Reproduce

Go to https://voila-dashboards.github.io/voici-demo/voila/render/demo.html?theme=dark

## Expected behavior

The spinner should be shown in the dark background

**Comment by martinRenou** [comment]
I think we should reuse/reimplement the JupyterLab splash screen logic for that, though it may be something to implement in Voila directly.
