### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voici#4]
We need documentation. It would be great if we could solve https://github.com/voila-dashboards/voici/issues/1 first and use jupyterlite-sphinx with Voici.

**Comment by jtpio** [comment]
FYI @martinRenou I enabled the Voici project on ReadTheDocs and invite you to be a maintainer.

**Comment by jtpio** [comment]
This ReadTheDocs environment would indeed be useful for deploying the static demo dashboards and testing PRs.
