### ISSUE TITLE
Cant open a file (csv, png) because the tree organisation of Voici's Build is unknow

### ISSUE THREAD

**Issue by Peter-Fialaire** [voila-dashboards/voici#40]
## Description
Good morning
I used the Voici template to create my repository that will allow me to support my Github page.
In the 'content' folder I put my Notebook, but also useful files: csv and png.
My problem is that I can't open those files: open("title.csv".. I get a FileNotFoundError.
I guess Voici builds another tree and puts my csv and png files in an other  folder (files?).
I tried a lot of combination to open my file like:
"../../files/file.csv" but it didn't work. Could you please help me.
THANKS
![image](https://user-images.githubusercontent.com/115087809/226104931-ea7b85df-0931-4c62-ae96-cc0629ba36d1.png)

## Reproduce

* Here is my Repo : https://github.com/Peter-Fialaire/Voici_test4
(This Repo was created from the Repo of the Voici Github)

* Here is the URL of acces My Voici Dashbord presenting the Notebook in the 'Content' folder : 
https://peter-fialaire.github.io/Voici_test4/voici/tree/index.html

==> I tried the notebook named 'Voici_test.ipynb' to get all the URL in the Voici Environment.. but it didn't work : I can't see my csv file.

Could you please explain me where Voici put my cvs file wich was initialy in the content folder of my Repo ?

Thank You.

**Comment by jtpio** [comment]
Thanks @Peter-Fialaire for opening this issue.

I believe this is related to https://github.com/voila-dashboards/voici/issues/3. The service worker (used to make the files available to the kernel in Voici / JupyterLite) does not seem to be loaded at the moment.
