### ISSUE TITLE
Package on conda forge

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voici#57]
### Problem

For now `voici` is only available on PyPI.

### Proposed Solution

It would be great to have `voici` available on conda forge.

### Additional context

Probably blocked by the dependency on a `voila` pre-release: 

https://github.com/voila-dashboards/voici/blob/bfb048b9f3a8e3a0124c953d089aa3816d9c029d/pyproject.toml#L34

**Comment by trungleduc** [comment]
https://github.com/conda-forge/staged-recipes/pull/24398#event-10841258159
