### ISSUE TITLE
The "launch lite" link from readthedocs leads to a 404 Not Found

### ISSUE THREAD

**Issue by ogrisel** [voila-dashboards/voici#78]
## Reproduce

Go to https://voici.readthedocs.io/en/latest/ and click on the "launch lite" yellow badge. It goes to:

https://voici.readthedocs.io/en/latest/_static/lite/voici/tree.html

with:

> 404 Not Found
> You are browsing the documentation of voici. The documentation page you are looking for at /en/latest/_static/lite/voici/tree.html was not found. 

I assume that instead this link should have led to:

https://voila-dashboards.github.io/voici-demo/voici/render/demo.html

or something similar.

**Comment by jtpio** [comment]
Thanks @ogrisel for the report.

Normally this one should work: https://voici.readthedocs.io/en/latest/_static/lite/voici/tree/index.html

So it might just be a matter of updating the link in the docs. Would you like to open a PR? Thanks!

**Comment by ogrisel** [comment]
Sorry I have already too many open github PR/issues firefox tabs :)
