### ISSUE TITLE
Redirect initial URI to ipynb file or directory of ipynb files

### ISSUE THREAD

**Issue by glw** [voila-dashboards/voici#94]
## Description
After starting the python server `python -m http.server` the URI takes you to `http://localhost:8000/lab/index.html` which displays as a "file not found". Could the URI redirect to a ipynb file if only one exists or to a directory of ipynb files where the user selects the relevant file?

## Reproduce
1. voici build --contents notebooks
2. cd _output
3. start server `python -m http.server`
4. Go to URI http://localhost:8000/lab/index.html

## Expected behavior

URI should take you to directory of ipynb files or straight to displaying a ipynb file.

## Context

- voila version: 0.5.0a4
- Operating System and version: Ubuntu 22.04.2 LTS on WSL2
- Browser and version: Microsoft Edge, Version 117.0.2045.31 (Official build) (64-bit)

## Troubleshoot Output

Work around is to go to base URI http://localhost:8000. This presents you a directory of ipynb files which can then be opened in browser.

**Comment by glw** [comment]
Checked the voici-demo repo and that redirects to the directory correctly.

**Comment by trungleduc** [comment]
Hi, can you try with Voici 0.5.0?
